#ddev-generated

RUN apt update && \
    apt install -y --no-install-recommends ansible && \
    rm -rf /var/lib/apt/lists/*

USER $username

# TODO: Require a stable version
RUN composer global require --no-cache upstreamable/ddev-basin-deploy:dev-main && \
  ansible-galaxy install ansistrano.deploy

# Switch back to root for other dockerfiles
USER root
