#!/usr/bin/env sh

#ddev-generated
## Description: Run a deploy of the current code
## Usage: basin-deploy
## Example: "ddev basin-deploy production"

DDEV_ANSIBLE_ENVIRONMENT="${1:-production}" ansible-playbook "${DDEV_APPROOT}/.ddev/deploy.yaml" "--inventory=${ANSIBLE_REMOTE_HOST},"
