#!/usr/bin/env sh

#ddev-generated
## Description: Create a new deploy
## Usage: basin-deploy
## Example: "ddev basin-deploy"

DDEV_ANSIBLE_ENVIRONMENT="${1:-production}" ansible-playbook "${DDEV_APPROOT}/.ddev/deploy.yml" "--inventory=${ANSIBLE_REMOTE_HOST},"
